version: "3.3"
services:
  webapp:
        build:
            context: ./app
            dockerfile: Dockerfile-app
        ports:
            - "9000:9000"
  client:
        build:
            context: ./client
            dockerfile: Dockerfile-client
        ports:
            - "3000:3000"
        links:
            - webapp
  mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        command: mongod --noauth
