version: "3.3"
services:
  webapp:
        image: webapp-api
        ports:
            - "9000:9000"
  client:
        image: webapp-client
        ports:
            - "3000:3000"
        links:
            - webapp
